# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Analytics for Accountants
author: Dr. Vic Anand, Ph.D.
copyright: "2025"
logo: BookLogo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", NotInBuild]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/vanand74/Accounting-Analytics-Textbook  # Online location of your book
  path_to_book: "Accounting-Analytics-Textbook"  # Optional path to your book, relative to the repository root


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


## For Google Analytics
html:
  analytics:
    google_analytics_id: G-VPK8SCQQVD
